export const Message = {
    notFound: 'Not Found',
    registerSuccessfully: 'Successfully Registered',
    inValid: 'Invalid Credentials',
    successfullyUpdate: 'Updated Successfully',
    alreadyExist: 'Already Exist',
    userNotGet: 'Fetching Error User',
    notCreated: 'Not Created',
    notUpdated: ' Not Updated',
    notDeleted: ' Not Deleted',
    notRegistered: 'User Not Registered',
    wrongPassword: 'Wrong Password',
    loginSuccessfully: 'Login Successfully',
    loginError: 'Login Error',
    notUpdate: 'Update Failed',
    serverError: 'Internal Server Error',
    emailNotFound: 'Invalid Email Address',
    emailAlreadyRegistered: 'Email Already Registered',
    phoneNumberAlreadyRegistered: 'Phone Number Already Registered',
    userIdNotFound: 'User Id Not Found',
    userNotFound: 'User Not Found',
    incorrrectPassword: 'Incorrect Password',
    inValidData: 'Invalid Data',
    duplicateData: 'Duplicate Data',
    success: "Success"
}